<a href="https://colab.research.google.com/github/YJay94/JAVA/blob/main/%EB%8F%99%EA%B8%B0%ED%9A%8C%EC%8B%9D%20%EC%A0%95%EC%82%B0%EC%BD%94%EB%93%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# 이석원 - 1차 늦게옴
# 신우주 - 1차 늦게옴
# 김성환 - 1차 늦게옴
# 김진우 - 1차 늦게옴, 중간에감(8시)
# 도수호 - 1차 중간에감(9시)
# 손은성 - 1차 중간에감(9시30분)
# 최진영 - 2차 사이다 한캔만마시고 바로감
# 천예원 - 2차 술안마심


arr_list = ["양준혁", "권나연", "박세훈", "서지훈", "안채영", "오재곤", "이충현", "정은우", "최규진", "최진영", 
            "이성은", "장혜원", "최형준", "이석원", "신우주", "김성환", "김진우", "도수호", "손은성", "정다은",
            "오지원", "천예원"]

# 1차 440,000
price_first = 440000
arr_first = ["양준혁", "권나연", "박세훈", "서지훈", "안채영", "오재곤",
	           "이충현", "정은우", "최규진", "최진영", "이성은", "장혜원", "최형준"]
dic_first_plus = {"이석원":15000, "신우주":15000, "김성환":15000, "김진우":10000, "도수호":23000, "손은성":24000}
sum_first_plus = 0
for i in dic_first_plus:
  sum_first_plus += dic_first_plus[i];

# 추가인원 합 금액 : 102,000
# print(sum_first_plus)   

# 1차총액 - 추가인원 합금액 : 338,000
fit_price_first = price_first - sum_first_plus
# print(fit_price_first)

# 1차 인당금액 - 26,000
per_first_deposit = fit_price_first / len(arr_first)
# print(fit_price_first / len(arr_first))



# 2차 132,500
price_second = 132500
arr_second = ["권나연", "서지훈", "양준혁", "신우주", "이석원", "이충현", "정다은", "오지원", "최형준", "최규진"]
dic_second_plus = {"천예원":9000, "최진영":4000}
sum_second_plus = 0
for i in dic_second_plus:
  sum_second_plus += dic_second_plus[i];

# 추가인원 합 금액 : 13,000
# print(sum_second_plus) 

# 2차총액 - 추가인원 합금액 : 119,500
fit_price_second = price_second - sum_second_plus
# print(fit_price_second)

# 1차 인당금액 - 11,950
per_second_deposit = fit_price_second / len(arr_second)
# print(fit_price_second / len(arr_second));


dic = {}
total = 0
for i in  arr_list:
  sum = 0
  status = ""
  if( i in arr_first):
    sum += per_first_deposit
    status += "1차 초기멤버 "
  elif( i in list(dic_first_plus)):
    sum += dic_first_plus[i]
    status += "1차 후기멤버 "
  
  if( i in arr_second):
    sum += per_second_deposit
    status += "2차 초기멤버 "
  elif( i in list(dic_second_plus)):
    sum += dic_second_plus[i]
    status += "2차 수정멤버 "
  
  total += sum
  print(i, "님은", status, "입니다","\n", 
        "입금하실 금액은 ",int(sum), "원 입니다.", "\n","입금하실 계좌는 우리은행 1002251864984 양준혁 입니다","\n", )


# 결제금액 : 572,500
print("1차 결제금액 : ", price_first , " 2차 결제금액 : " , price_second)
print("총 결제금액 : ", price_first + price_second)

# 입금받는금액 : 572,500
print("입금받는금액 : ", int(total))

양준혁 님은 1차 초기멤버 2차 초기멤버  입니다
 입금하실 금액은  37950 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

권나연 님은 1차 초기멤버 2차 초기멤버  입니다
 입금하실 금액은  37950 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

박세훈 님은 1차 초기멤버  입니다
 입금하실 금액은  26000 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

서지훈 님은 1차 초기멤버 2차 초기멤버  입니다
 입금하실 금액은  37950 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

안채영 님은 1차 초기멤버  입니다
 입금하실 금액은  26000 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

오재곤 님은 1차 초기멤버  입니다
 입금하실 금액은  26000 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

이충현 님은 1차 초기멤버 2차 초기멤버  입니다
 입금하실 금액은  37950 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

정은우 님은 1차 초기멤버  입니다
 입금하실 금액은  26000 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

최규진 님은 1차 초기멤버 2차 초기멤버  입니다
 입금하실 금액은  37950 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

최진영 님은 1차 초기멤버 2차 수정멤버  입니다
 입금하실 금액은  30000 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

이성은 님은 1차 초기멤버  입니다
 입금하실 금액은  26000 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

장혜원 님은 1차 초기멤버  입니다
 입금하실 금액은  26000 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

최형준 님은 1차 초기멤버 2차 초기멤버  입니다
 입금하실 금액은  37950 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

이석원 님은 1차 후기멤버 2차 초기멤버  입니다
 입금하실 금액은  26950 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

신우주 님은 1차 후기멤버 2차 초기멤버  입니다
 입금하실 금액은  26950 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

김성환 님은 1차 후기멤버  입니다
 입금하실 금액은  15000 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

김진우 님은 1차 후기멤버  입니다
 입금하실 금액은  10000 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

도수호 님은 1차 후기멤버  입니다
 입금하실 금액은  23000 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

손은성 님은 1차 후기멤버  입니다
 입금하실 금액은  24000 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

정다은 님은 2차 초기멤버  입니다
 입금하실 금액은  11950 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

오지원 님은 2차 초기멤버  입니다
 입금하실 금액은  11950 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

천예원 님은 2차 수정멤버  입니다
 입금하실 금액은  9000 원 입니다.
 입금하실 계좌는 우리은행 1002251864984 양준혁 입니다

1차 결제금액 :  440000  2차 결제금액 :  132500
총 결제금액 :  572500
입금받는금액 :  572500